export { default as Hero } from "./hero/Hero";
export { default as About } from "./about/About";
export { default as Gallery } from "./gallery/Gallery";
export { default as Experience } from "./experience/Experience";
export { default as Projects } from "./projects/Projects";
export { default as Skills } from "./skills/Skills";
export { default as Blog } from "./blog/Blog";
export { default as Education } from "./education/Education";
export { default as Contact } from "./contact/Contact";
